### ISSUE TITLE
Can't login to JIRA cloud

### ISSUE THREAD

**Issue by AmmarCodes** [KensoDev/gong#7]
Hi,

I was trying to login to the company's JIRA cloud, but I got `Cloud not login`.

I've entered the email as my username, the domain I tried subdomain, full url and full url with `https://` prefix.

I still get the same error.

Am I missing something? is there any needed permission or option to be enabled from the administration side?

**Comment by KensoDev** [comment]
Checking....

What is the domain structure (you don't have to give me the full domain, I just want to test it out)

**Comment by KensoDev** [comment]
Here is my `~/.gong` file:

```
{
"client":"jira",
"domain":"https://YOUR_DOMAIN.atlassian.net",
"password":"REDACTED",
"project_prefix":"GLOB",
"username":"YOUR_EMAIL"
}
```

**Comment by KensoDev** [comment]
When you get prompted for the domain, you need to provide `x.atlassian.com` with no HTTPS or anything else.

Your email and full password should be provided and you can make sure all the details are correct in the config file `/.gong.json`

**Comment by AmmarCodes** [comment]
Here's my .gong content:
```
{  
  "client":"jira",
  "domain":"https://abc.atlassian.net/",
  "password":"123",
  "project_prefix":"WKA",
  "username":"my@email.com"
}
```

I checked that the content of .gong is correct.
When I try to `gong start WKA-123` I get this error:
```
❯ gong start WKA-103
Problem with starting the issue
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x12af276]

goroutine 1 [running]:
github.com/KensoDev/gong.Start(0x0, 0x0, 0x13b7a5e, 0x7, 0x7fff5fbffaa3, 0x7, 0x5, 0x4, 0xc42006ed90, 0x5)
        /Users/avizurel/Code/go/src/github.com/KensoDev/gong/client.go:46 +0x26
main.main.func2(0xc42001a9a0, 0x0, 0xc42001a9a0)
        /Users/avizurel/Code/go/src/github.com/kensodev/gong/cmd/gong/main.go:70 +0xd0
github.com/urfave/cli.HandleAction(0x1342800, 0xc420017240, 0xc42001a9a0, 0xc42006c300, 0x0)
        /Users/avizurel/Code/go/src/github.com/urfave/cli/app.go:491 +0xd4
github.com/urfave/cli.Command.Run(0x13b7296, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13c8724, 0x44, 0x0, ...)
        /Users/avizurel/Code/go/src/github.com/urfave/cli/command.go:212 +0xb6e
github.com/urfave/cli.(*App).Run(0xc4200de1a0, 0xc420010150, 0x3, 0x3, 0x0, 0x0)
        /Users/avizurel/Code/go/src/github.com/urfave/cli/app.go:256 +0x76f
main.main()
        /Users/avizurel/Code/go/src/github.com/kensodev/gong/cmd/gong/main.go:234 +0x368
```

**Comment by KensoDev** [comment]
@AAlakkad I think I understand now.
Can you tell me what are the transitions the issue can go through on Jira?

**Comment by AmmarCodes** [comment]
"To Do", "In Progress", "Done", "Quality Assurance", "Closed", "Reopened".
It could be different depending on the project.

**Comment by KensoDev** [comment]
https://github.com/KensoDev/gong/blob/develop/jira.go#L130

This is the bug.

The transitions you can go through are hard coded unfortunately. 
I've been meaning to go ahead and change that. Didn't get around to it yet.

**Comment by AmmarCodes** [comment]
Aha, that explain it :)

**Comment by AmmarCodes** [comment]
So if I wanted to use a local forked version, which transitions should I replace the `allowed` variable? is it "To Do" and "In Progress"?

**Comment by KensoDev** [comment]
The steps you want to go through until you consider it "started"

**Comment by KensoDev** [comment]
I would love for this to be a config though.

**Comment by AmmarCodes** [comment]
I think it would be perfect, maybe per project since it could be different?

**Comment by AmmarCodes** [comment]
I'm trying to build the package, executing:
`go get` inside `gong` project or `gong/cmd/gong`, but getting:

```
go install: no install location for directory /Users/ammar/Projects/gong/cmd/gong outside GOPATH
        For more details see: 'go help gopath'
```

Is there a quick fix I can do?
If it takes a lot from your time just ignore it, I'll wait for the config file :)

**Comment by KensoDev** [comment]
you likely don't have `$GOPATH` configured correctly (from what I understand from the command here`.

**Comment by KensoDev** [comment]
https://github.com/KensoDev/gong/releases/tag/1.6.0

https://github.com/KensoDev/gong/commit/04b0007556434cc83b56cbbdcc7b397fd8b98b6a

I really did not test this out properly.

Also, it prints out the list of transitions for you, just to make sure you have the correct configurations.

Another option I was thinking about is to confirm the list of transitions the first time and then just ask the user when they start a task.

**Comment by AmmarCodes** [comment]
I'm getting this error when I try to login (after removing `~/.gong.json`):
```
panic: runtime error: index out of range

goroutine 1 [running]:
main.main.func1(0xc420080840, 0x0, 0xc420080840)
        /Users/avizurel/Code/go/src/github.com/kensodev/gong/cmd/gong/main.go:25 +0x1a0
github.com/urfave/cli.HandleAction(0x13428c0, 0x13ca448, 0xc420080840, 0xc42006c300, 0x0)
        /Users/avizurel/Code/go/src/github.com/urfave/cli/app.go:491 +0xd4
github.com/urfave/cli.Command.Run(0x13b72fc, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13c5209, 0x2d, 0x0, ...)
        /Users/avizurel/Code/go/src/github.com/urfave/cli/command.go:212 +0xb6e
github.com/urfave/cli.(*App).Run(0xc4200dc1a0, 0xc42000c2a0, 0x2, 0x2, 0x0, 0x0)
        /Users/avizurel/Code/go/src/github.com/urfave/cli/app.go:256 +0x76f
main.main()
        /Users/avizurel/Code/go/src/github.com/kensodev/gong/cmd/gong/main.go:234 +0x368
```

**Comment by KensoDev** [comment]
I'll test tomorrow

**Comment by KensoDev** [comment]
After you delete the `/.gong.json` file, you will need to run `gong login jira` again to recreate it.

Here's what mine looks after recreation:

```
{
  "client":"jira",
  "domain":"https://YOUR_DOMAIN.atlassian.net",
  "password":"PASS",
  "project_prefix":"GLOB",
  "transitions":"Ready,Start",
  "username":"EMAIL"
}
```

**Comment by KensoDev** [comment]
The transition is working great, all you need to do it input the transition you need to go through when you do `gong start` and the rest is taken care of.

You need to input the transition with no spaces.

**Comment by AmmarCodes** [comment]
I installed a fresh version from the releases tab, also deleted the `~/.gong.json`, when I try to login I get:

```
❯ ~/Downloads/gong_darwin_amd64 login
panic: runtime error: index out of range

goroutine 1 [running]:
main.main.func1(0xc42008c840, 0x0, 0xc42008c840)
	/Users/avizurel/Code/go/src/github.com/kensodev/gong/cmd/gong/main.go:25 +0x1a0
github.com/urfave/cli.HandleAction(0x13428c0, 0x13ca448, 0xc42008c840, 0xc42006c300, 0x0)
	/Users/avizurel/Code/go/src/github.com/urfave/cli/app.go:491 +0xd4
github.com/urfave/cli.Command.Run(0x13b72fc, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x13c5209, 0x2d, 0x0, ...)
	/Users/avizurel/Code/go/src/github.com/urfave/cli/command.go:212 +0xb6e
github.com/urfave/cli.(*App).Run(0xc420058ea0, 0xc42007e080, 0x2, 0x2, 0x0, 0x0)
	/Users/avizurel/Code/go/src/github.com/urfave/cli/app.go:256 +0x76f
main.main()
	/Users/avizurel/Code/go/src/github.com/kensodev/gong/cmd/gong/main.go:234 +0x368
```

Sorry I cause you a lot of troubles with this :D

**Comment by KensoDev** [comment]
You need to run 'gong login jira'

**Comment by AmmarCodes** [comment]
Sorry I always forget to add jira to the command!

I tried couple times and still can't login.
```
❯ ~/Downloads/gong_darwin_amd64 login jira
Please enter your jira password: ***********
Please enter your jira project_prefix: WKA
Please enter your jira transitions: ToDo,InProgress
Please enter your jira username: *********************
Please enter your jira domain: **********************
Cloud not login
```

I checked the `~/.gong.json` and it's content is correct, it's as yours but with different values.

**Comment by KensoDev** [comment]
I'll add some print to the login failed reason. Weird. Can you post the content of your gong.json file? No password and domain prefix obviously

**Comment by AmmarCodes** [comment]
```
{"client":"jira","domain":"https://xxx.atlassian.net","password":"123","project_prefix":"WKA","transitions":"ToDo,InProgress","username":"my@email.com"}
```

**Comment by AmmarCodes** [comment]
I'm very sorry, there was a problem with the password I'm using. the login is working now.

**Comment by KensoDev** [comment]
Thank you for letting me know.
Hope you enjoy using this product.
